# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df30eb186451611b911f0624a9606629a0d8a57186cd2a421afb7376518fe190a9d20bdf23e51fb3d2c5e0e1f4185aa6cbec84e885c485ad18f0d4ec25785fcf

test:
  secret_key_base: 0ed1a0ee809c2126d5c1f4a6891f8056d7ad3acce930c150d281f253118db08fa59244e3e5bd672e44250f97a45301e58eb528cdd1e448cb978da69348a58e5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
